name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
        port: 22
        script: |
          ls
          export NVM_DIR="/home/slasher/.nvm"
          source "$NVM_DIR/nvm.sh"
          cd 1vs1
          cd 1-vs-1
          git pull origin main
          npx prisma generate
          npm install
          cd ..
          pm2 restart all
        